/*
# Copyright(C) The PEER Group Inc., 2023.
#
# This software contains confidential and trade secret information
# belonging to PEER Group Inc, All Rights Reserved.
#
# No part of this software may be reproduced or transmitted in any form
# or by any means, electronic, mechanical, photocopying, recording or
# otherwise, without the prior written consent of the PEER Group Inc.
*/

const { test, expect, TestInfo } = require('@playwright/test');

const { signInAsAuthorizedUser, navigateToHomePage, navigateToFromNavigationBar, measurePerformance, signOut, takeScreenshot } = require("./common-methods.js");

const config = require("../configuration/config.json");

const testName = 'EF Web Client Test: Create a new private project @smoke @happyPath @R91';

const toolId = config.cassetteToolId;

test(testName, async ({ page }, TestInfo) => {
   
    var timestamp = Date.now();
    var localTime = new Date(timestamp);

    // Add a unique generated name to the collection
    var isoDateString = new Date().toISOString();
    console.log(isoDateString);
    let currentDate = isoDateString;
    let generatedModuleName = 'MODULE_TYPE_R9.1_' + currentDate;
    console.log('The MODULE TYPE Name: ' + generatedModuleName);

  
 
    console.log("Test started...:" + testName + localTime);

    // Navigate to the home page for test
    await navigateToHomePage(page, config.testingUrl); 

    // TO DO: could be passed in as an arg
    await signInAsAuthorizedUser(page, config.userNameQA3);

    await page.getByRole('link', { name: 'Module Types' }).click();
    await page.getByRole('button', { name: 'New' }).click();
    await page.locator('#clr-input-2').click();
    await page.locator('#clr-input-2').fill(generatedModuleName);
    await page.locator('#clr-input-2').press('Enter');
    await page.locator('#clr-input-3').click();
    await page.locator('#clr-input-3').fill('Module Short Name ' + currentDate);
    await page.locator('#clr-input-3').press('Enter');
    await page.locator('#clr-textarea-0').click();
    await page.locator('#clr-textarea-0').fill('Description for the module generated by automation on ' + currentDate);
    await page.locator('#clr-textarea-0').press('Enter');
    await page.locator('.card-text').click();
    await page.locator('.card-text').click();
    await page.locator('.clr-row').first().click();
    await page.getByRole('button', { name: 'Save' }).click();
    await page.getByRole('button', { name: 'Back' }).click();

    await signOut(page);
  
    await measurePerformance(page, TestInfo);

 });