name: .NET Playwright Tests
on:
  workflow_dispatch:
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore
      working-directory: pf-evatec-e2e-automated-tests
      run: dotnet restore

    - name: Build
      working-directory: pf-evatec-e2e-automated-tests
      run: dotnet build --no-restore

    - name: Install Playwright Browsers
      working-directory: pf-evatec-e2e-automated-tests
      run: pwsh bin/Debug/net8.0/playwright.ps1 install --with-deps

    - name: Run .NET Playwright tests
      working-directory: pf-evatec-e2e-automated-tests
      run: dotnet test --no-build --logger "trx;LogFileName=test-results.trx"

    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: dotnet-playwright-test-results
        path: |
          pf-evatec-e2e-automated-tests/TestResults/
          pf-evatec-e2e-automated-tests/**/artifacts/
        retention-days: 30
